theme: jekyll-theme-dinky

title: <a href='/tiw8/2025'>TIW 8</a>
description:
  [
    <p>Technologies Web synchrones et multi-dispositifs</p><ul><li><a href='/tiw8/2025/#plan-du-cours'>Cours</a></li><li><a href='/tiw8/2025/#tp'>TP</a></li><li><a href='/tiw8/2025/#evaluation'>Evaluation</a></li></ul>,
  ]
